### PR TITLE
Expanded contributing docs

### PR DESCRIPTION
**Pull request by ericelliott**
@nkbt

### CODE REVIEW

**Comment by ericelliott** [comment]
LOL at merging the first doc expansion without following the process I'm documenting. ;)

**Comment by nkbt** [comment]
Oh yeah. I'd ask to make line breaks =). Long lines suck. In md single line break is equivalent to a space, so it is safe to do those.

I reckon you could fix those lines in README.md in this PR

**Comment by ericelliott** [comment]
I'm not sure what you mean. Do you mean we should add line breaks to the README file as opposed to word-wrap? If so, I disagree. All the viewers I use know how to wrap lines.

If you mean we should add a line length suggestion to the contributing doc for sourcecode, that should be a lint rule, instead.

**Comment by nkbt** [comment]
Editors yes, but in github's (and other's) PRs long lines are pretty big pain to review. So yes, I would add some line length check for both code (js, css, etc) and docs.

I'll merge this one in though cause it is totally fine by itself

**Comment by nkbt** [comment]
Hm, I see that Github wraps lines. I am pretty sure it was not the case not so long ago...

**Comment by nkbt** [comment]
Question aside: are you ok with deleting merged in branches?

**Comment by ericelliott** [comment]
Yes.

**Pull request merged**
